name: Main Workflow

on:
  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: First job step
        run: echo "Running main job first step"

  call_second_job:
    needs: main_job
    uses: ./.github/workflows/second_job.yaml
